### ISSUE TITLE
Issue with part 6 cancel button

### ISSUE THREAD

**Issue by ErlendLandro** [warpech/HelloWorld#21]
After adding the <code>this.Expense.Clear()</code> to the Cancel button handler all expenses in the view are deleted. Without it we hit a connection error. Example:
![error](https://cloud.githubusercontent.com/assets/19392292/19680893/a10ac69a-9aa7-11e6-889b-b7d50651143e.gif)

Is there a simple, easy to understand solution we can implement here?

**Comment by warpech** [comment]
I will take a look, thanks for the detailed description.

**Comment by warpech** [comment]
> Without it we hit a connection error.

Let me start by explaining what actually happens. It is not that we hit a connection error. We hit a server side exception:

```
Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.
Version: 2.2.1.3234.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4174.
   at Starcounter.Internal.DbState.ReadString(UInt64 oid, UInt64 address, Int32 index) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\Internal\DbState.cs:line 595
   at HelloWorld.Expense.get_Description()
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 208
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 330
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\TransactionManager.cs:line 487
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 139
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 245
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 306
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\TransactionManager.cs:line 487
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 139
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 380
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 86
   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 111
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 90
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 64
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
ErrorCode=4174
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4174
```

A server side exception breaks the WebSocket, and that causes the connection error.

The reason for the exception is a known issue in Starcounter. It is explained here: https://github.com/Starcounter/Starcounter/issues/3760

I believe that your solution `this.Expense.Clear()` is the right one and needs to stay.

**Comment by ErlendLandro** [comment]
Okay, got it. Wouldn't we need to update the view to get the expense fields back after we have used <code>.Clear()</code>?

**Comment by warpech** [comment]
Starcounter's TypedJSON auto binding does that automatically.

**Comment by ErlendLandro** [comment]
It seemingly does not. In order to get the expenses list back in the view I have to do a solution like this:

``` cs
        void Handle(Input.Cancel action)
        {
            Transaction.Rollback();
            this.Expenses.Clear();
            var person = (Person)this.Data;
            foreach (var expense in person.Spendings)
            {
                var expenseJson = Self.GET("/HelloWorld/partial/expense/" + expense.GetObjectID());
                this.Expenses.Add(expenseJson);
            }
        }
```

It's probably not what we want.
@ubbeK

**Comment by warpech** [comment]
You are absolutely right. We can write it in a slightly DRY-er way, though.

Notice that I introduced `, IBound<Person>`. This would need to be actually added in one of the previous steps.

**Program.cs**

```
            Handle.GET("/HelloWorld", () =>
            {
                return Db.Scope(() =>
                {
                    var person = Db.SQL<Person>("SELECT p FROM Person p").First;
                    var json = new PersonJson()
                    {
                        Data = person
                    };

                    if (Session.Current == null)
                    {
                        Session.Current = new Session(SessionOptions.PatchVersioning);
                    }
                    json.Session = Session.Current;
                    json.RefreshExpenses(person.Spendings);
                    return json;
                });
            });
```

**PersonJson.json.cs**

``` cs
using System.Collections.Generic;
using Starcounter;

namespace HelloWorld
{
    partial class PersonJson : Json, IBound<Person>
    {
        public string FullName => FirstName + " " + LastName;

        void Handle(Input.Save action)
        {
            Transaction.Commit();
        }

        void Handle(Input.Cancel action)
        {
            Transaction.Rollback();
            RefreshExpenses(this.Data.Spendings);
        }

        void Handle(Input.AddNewExpense action)
        {
            var expense = new Expense()
            {
                Spender = this.Data,
                Amount = 1
            };
            AddExpense(expense);
        }

        void Handle(Input.DeleteAll action)
        {
            Db.SlowSQL("DELETE FROM Expense WHERE Spender = ?", this.Data);
            RefreshExpenses(this.Data.Spendings);
        }

        public void RefreshExpenses(IEnumerable<Expense> expenses)
        {
            this.Expenses.Clear();
            foreach (Expense expense in expenses)
            {
                AddExpense(expense);
            }
        }

        public void AddExpense(Expense expense)
        {
            var expenseJson = Self.GET("/HelloWorld/partial/expense/" + expense.GetObjectID());
            this.Expenses.Add(expenseJson);
        }
    }
}
```

**Comment by ErlendLandro** [comment]
I'll add this to the repo and to the tutorial tomorrow morning or tonight. I appreciate the help!
