### ISSUE TITLE
Cannot use sample apps after Hello World is stopped

### ISSUE THREAD

**Issue by warpech** [warpech/HelloWorld#50]
Steps to reproduce:

1. Start Hello World
2. Stop Hello World
3. Start Launcher, People and SignIn
4. Sign in with a user
5. Go to http://localhost:8080/people/persons
6. You will get the following exception

```
Starcounter.DbException: ScErrSchemaCodeMismatch (SCERR4177): Operation failed because input does not match schema. CLR Class is not loaded for table HelloWorld.Spender
Version: 2.3.0.6120.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4177.
   at Starcounter.Binding.Bindings.CreateExceptionOnTypeDefNotFound(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Binding\Bindings.cs:line 485
   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Binding\Bindings.cs:line 353
   at Starcounter.Enumerator.MoveNext() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Mock\Enumerator.cs:line 239
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 479
   at Starcounter.Query.Execution.Sort.CreateEnumerator() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
   at Starcounter.Query.Execution.Sort.MoveNext() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 145
   at Starcounter.Json.Array_InitializeAfterImplicitConversion(Json parent, TObjArr template) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Array.cs:line 79
   at Starcounter.Templates.TArray`1.BoundOrUnboundSet(Json parent, Arr`1 value) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Templates\TArray.cs:line 119
   at People.PersonsPage.set_Persons(Arr`1 value) in c:\www\People\src\People\obj\x64\Debug\ViewModels\ViewModels\PersonsPage.json:line 20
   at People.PersonsPage.RefreshPersons() in c:\www\People\src\People\ViewModels\PersonsPage.json.cs:line 20
   at People.PartialHandlers.<>c.<Register>b__0_1() in c:\www\People\src\People\Api\PartialHandlers.cs:line 39
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 341
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1133
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET[T](String uri, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Internal\Rest\Self.cs:line 22
   at People.MainHandlers.GetLauncherPage(String Url, Boolean DbScope) in c:\www\People\src\People\Api\MainHandlers.cs:line 138
   at People.MainHandlers.<>c.<Register>b__0_5() in c:\www\People\src\People\Api\MainHandlers.cs:line 65
   at People.AuthorizedHandle.<>c__DisplayClass0_0.<GET>b__1() in c:\www\People\src\People\Helpers\AuthorizedHandle.cs:line 9
   at People.AuthorizedHandle.TrySignIn(Func`1 code) in c:\www\People\src\People\Helpers\AuthorizedHandle.cs:line 21
   at People.AuthorizedHandle.<>c__DisplayClass0_0.<GET>b__0() in c:\www\People\src\People\Helpers\AuthorizedHandle.cs:line 9
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 341
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
ErrorCode=4177
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4177

More information about this error may be available in the server error log.
```

**Comment by warpech** [comment]
This is the same problem as https://github.com/Starcounter/Level1/issues/3449

**Comment by ErlendLandro** [comment]
For the same reason why Starcounter/Level1#3449 was closed, I'm closing this one

**Comment by warpech** [comment]
Actually, I believe that this was only a problem when Hello World used database classes that extended `Simplified.Ring1.Something`. 

Otherwise this error does not have a reason to occur here.
